config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :pics, only: [:index, :new, :create, :edit, :update ,:destroy] do
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
  end
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  mount_uploader :avatar, AvatarUploader
#  has_many :pics, dependent: :destroy
has_many :pics
  has_many :comments, dependent: :destroy

 # has_many :relationships, foreign_key: "follower_id", dependent: :destroy
 # has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
 # has_many :followed_users, through: :relationships, source: :followed
 # has_many :followers, through: :reverse_relationships, source: :follower

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  def self.create_unique_string
    SecureRandom.uuid
  end
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
#  def follow!(other_user)
#    relationships.create!(followed_id: other_user.id)
#  end
#  def following?(other_user)
#    relationships.find_by(followed_id: other_user.id)
#  end
#  def unfollow!(other_user)
#    relationships.find_by(followed_id: other_user.id).destroy
#  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pic, only: [:edit, :update, :destroy]

  def index
    @pics = Pic.all
  end

  def new
    @pic = Pic.new
  end

  def create
    @pic  = Pic.new(pics_params)
    @pic.user_id = current_user.id
    if @pic.save
      redirect_to pics_path, notice: "写真を作成しました！"
#      NoticeMailer.sendmail_Pic(@Pic).deliver
    else
      render 'new'
    end
  end

  def edit
    # edit, update, destroyで共通コード
    if(@pic.user_id == current_user.id)
      @pic = Pic.find(params[:id])
    else
      redirect_to pics_path, notice: "自分の投稿以外は編集できません"
    end
  end

  def update
    # edit, update, destroyで共通コード
    @pic = Pic.find(params[:id])

    if @pic.update(pics_params)
      redirect_to pics_path, notice: "写真を更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    # edit, update, destroyで共通コード
    @pic = Pic.find(params[:id])
    @pic.destroy
    redirect_to pics_path, notice: "写真を削除しました！"
  end

  private
    def pics_params
      params.require(:pic).permit(:title, :content, :image, :image_cache)
    end

    # idをキーとして値を取得するメソッド
    def set_pic
      @pic = Pic.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/pics_helper.rb
module PicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pics_path
    elsif action_name == 'edit'
      pic_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <ul>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "写真", pics_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
    </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  </header>

<%= yield %>

  <footer>
    <p>© 2017 Copyright obenkyo Corp.</p>
  </footer>

</body>
</html>

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>

<% if @pic.errors.any? %>
  <div id="error_explanation">
    <h2><%= @pic.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @pic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :タイトル %>
<%= f.text_field :title, class: 'form-control' %>
<br>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>

<%= f.label :投稿写真 %>
<%= image_tag @pic.image.url if @pic.image? %>
<%= f.file_field :image %>
<%= f.hidden_field :image_cache %>
<br>

<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>
<%= link_to "写真一覧画面にもどる", pics_path %>

app/views/pics/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@pic) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @pic.title %></p>
      <p>本文:<%= @pic.content %></p>
      <%= f.submit "登録" %>
    <% end %>
    <%= form_for(@pic, url: new_pic_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back' %>
    <% end %>
  </div>
</div>

app/views/pics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿を変更する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p id="notice"><%= notice %></p>
    <h1>写真一覧</h1>
      <%= link_to "写真を投稿する", new_pic_path, class: 'btn btn-default' %>
    <% @pics.each do |pic| %>
    <div class="row">
      <% if pic.image? %>
        <%= image_tag(pic.image) %>
      <% end %>
      <h5><%= pic.user.name %></h5>
      <h4><strong><%= pic.title %></strong></h4>
      <p><%= pic.content %></p>
      <% if pic.user_id == current_user.id %>
        <%= link_to "編集", edit_pic_path(pic.id), class: 'btn btn-sm btn-success' %>
        <%= link_to "削除", pic_path(pic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-sm btn-danger' %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/pics/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真を投稿する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<section class="main-header">
  <p class="flash"><%= notice %><%= alert %></p>
  <img src="<%= asset_path "insta.png" %>">
</section>
<section class="about">
  <h1>About お勉強Instagram</h1>
  <p>
     写真投稿だよ<br>
     インスタ映えするのをアップしよう。
  </p>
</section>
<section class="function container-fluid">
  <div class="row">
  <h1>お勉強Instagramについて</h1>
      <div class="col-md-3 col-sm-6">
          <p>サポート</p>
      </div>
      <div class="col-md-3 col-sm-6">
          <p>ブログ</p>
      </div>
      <div class="col-md-3 col-sm-6">
          <p>プレス</p>
      </div>
      <div class="col-md-3 col-sm-6">
          <p>API</p>
      </div>
    </div>
</section>